DEFAULT_CONFIG_FILE="quantbox.config"

OPEN_INSIDE_BODY_GREEN = 1
OPEN_NEAR_HIGH_WICK_GREEN = 2
OPEN_NEAR_LOW_WICK_GREEN = 3
OPEN_GAP_UP = 4
OPEN_GAP_DOWN = 5
OPEN_INSIDE_BODY_RED = 6
OPEN_NEAR_HIGH_WICK_RED = 7
OPEN_NEAR_LOW_WICK_RED = 8
DOJI=9
